#!/bin/bash
# Check we have we need
command -v upx >/dev/null 2>&1 || { echo >&2 "I require upx but it's not installed.  Aborting."; exit 1; }
command -v grep >/dev/null 2>&1 || { echo >&2 "I require grep but it's not installed.  Aborting."; exit 1; }
command -v bash >/dev/null 2>&1 || { echo >&2 "I require bash but it's not installed.  Aborting."; exit 1; }
command -v find >/dev/null 2>&1 || { echo >&2 "I require find but it's not installed.  Aborting."; exit 1; }
command -v file >/dev/null 2>&1 || { echo >&2 "I require file but it's not installed.  Aborting."; exit 1; }

#
echo Finding files...; find $1 -type f | while read -r file ; do file $file | grep 'Mach-O 64-bit exec' | gawk '{ print "chmod +w " $1 " ; upx -9 " $1 " ; chmod -w " $1}' | tr -d ':'  >> $1.upxpack ; done ; echo Packing files... ;  source $1.upxpack  ; rm $1.upxpack
